[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:backend]
command=python -m uvicorn app.main:app --host 0.0.0.0 --port 8001 --log-level info
directory=/app/backend
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=DATABASE_URL="%(ENV_DATABASE_URL)s",SECRET_KEY="%(ENV_SECRET_KEY)s",ENVIRONMENT="%(ENV_ENVIRONMENT)s",BACKEND_CORS_ORIGINS="%(ENV_BACKEND_CORS_ORIGINS)s"

[program:frontend]
command=node node_modules/.bin/next start --port %(ENV_PORT)s --hostname 0.0.0.0
directory=/app/frontend
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
